@api = http://localhost:1500
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliZjczNzg4OTNkNDJlODZkMjRiMTAiLCJ1c2VyTmFtZSI6IklzYWFjIiwidXNlclJvbGVJZCI6IjYxOWJmNjhlNjQzNWRmOGUwMDFiYmE3NSIsImlhdCI6MTYzNzc3NzQ1NSwiZXhwIjoxNjM3Nzc4NjU1fQ.z_2BeYJVtOuPdjH_DIG-yQ9VPAIJmcvo6KZ600DzJfU
@refreshToken = ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliZjczNzg4OTNkNDJlODZkMjRiMTAiLCJpYXQiOjE2Mzc2MjA5NTMsImV4cCI6MTYzNzcwNzM1M30.z1whzNBJxgelzsA-GfEDPxmTbREh5mLmf0gtaGlPT24
### Login
POST {{api}}/api/auth
Content-Type: application/json

{
    "password": "123456",
    "email": "isaac4@gmail.com"
}

### Ping
GET {{api}}/api/company/ping

###Get company by id
GET {{api}}/api/company/619d4e58076745b18180ec8f
Authorization: {{token}}

### Get all companies
GET {{api}}/api/company
Authorization: {{token}}

### Create company
POST {{api}}/api/company
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Sony",
    "description": "Owner of Play Station"
}

### Update company
PUT {{api}}/api/company/619d4e58076745b18180ec8f
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Nintendo",
    "description" : "Nintendo2"
}

### Delete company
DELETE {{api}}/api/company/619e82db47103a03fb650b1a
Authorization: {{token}}

